ecs/README.md, ecs/start_ecs_cluster.sh
1. Updated README.MD for ECS
2. Added configuration for ecs-cli 
=> Ecs changes

build.gradle, src/main/java/com/amazon/aws/cqlreplicator/models/PrimaryKey.java, src/main/java/com/amazon/aws/cqlreplicator/storage/SourceStorageOnCassandra.java, src/main/java/com/amazon/aws/cqlreplicator/storage/TargetStorageOnKeyspaces.java, src/main/java/com/amazon/aws/cqlreplicator/task/replication/CassandraReplicationTask.java
Added exception ArrayIndexOutofBoundsException handling, removed unused imports
=> Added exception ArrayIndexOutofBoundsException handling

spark/README.MD, src/main/conf/CassandraConnector.conf, src/main/java/com/amazon/aws/cqlreplicator/storage/SourceStorageOnCassandra.java, src/main/java/com/amazon/aws/cqlreplicator/task/replication/PartitionDiscoveryTask.java
=> RandomToken support

README.MD, copilot/cql-replicator-service/manifest.yml, copilot/environments/test/manifest.yml, docker/Dockerfile, gradle.properties, pom.xml, src/main/conf/config.properties, src/main/java/com/amazon/aws/cqlreplicator/CloudWatchCustomMetrics.java, src/main/java/com/amazon/aws/cqlreplicator/PreflightCheck.java, src/main/java/com/amazon/aws/cqlreplicator/Starter.java, src/main/java/com/amazon/aws/cqlreplicator/Stopper.java, src/main/java/com/amazon/aws/cqlreplicator/connector/ConnectionFactory.java, src/main/java/com/amazon/aws/cqlreplicator/models/PrimaryKey.java, src/main/java/com/amazon/aws/cqlreplicator/storage/StorageServiceImpl.java, src/main/java/com/amazon/aws/cqlreplicator/storage/TargetStorageLargeObjectsOnS3.java, src/main/java/com/amazon/aws/cqlreplicator/storage/TargetStorageOnKeyspaces.java, src/main/java/com/amazon/aws/cqlreplicator/task/replication/DeletedRowDiscoveryTask.java, src/main/java/com/amazon/aws/cqlreplicator/task/replication/PartitionDiscoveryTaskV2.java, src/main/java/com/amazon/aws/cqlreplicator/task/replication/RowDiscoveryTaskV2.java, src/main/java/com/amazon/aws/cqlreplicator/util/ApiEndpoints.java, src/main/java/com/amazon/aws/cqlreplicator/util/LevelDBPageIterator.java, src/main/java/com/amazon/aws/cqlreplicator/util/Utils.java, src/test/README.MD
*Issue # 23*
1. Added support for C* tables with no regular columns, `WRITETIME_COLUMNS` set to `NONE`
2. Fix the issue with ThreadPool for delete operations, no it's a single-threaded process
3. Updated README.MD
4. Set bucket name, keyspace, and table via environmental variables once to improve deployment experience via aws copilot
5. Fixed the issue with LevelDB page reader
=> 23 support tables without regular columns

glue/README.MD
=> Updated README.MD

glue/sbin/CQLReplicator.scala
Fixed the issue with S3, xref is empty
=> Fixed the issue with S3 support, xref column is empty

glue/bin/cqlreplicator, glue/sbin/CQLReplicator.scala
1/ Replaced non-function while(true) to Scala Iterator
2/ Formatted
3/ Updated cqlreplicator  
=> Replaced while(true) by Iterator.continually(stopRequested)

glue/README.MD, glue/bin/cqlreplicator, glue/sbin/CQLReplicator.scala
Updated rowToStatement function, fixed README.MD
=> 44 optimize rowtostatement

glue/README.MD, glue/bin/cqlreplicator, glue/sbin/keyspaces/CQLReplicator.scala, glue/sbin/parquet/CQLReplicator.scala
- Added checks for OS.
- Added a new flag to skip glue connector creation.
- Reformatted code. 
- Updated README.MD.
CQlReplicator duplicates UPSERTs requests. 
=> - Fixed the issue with duplicated requests.

glue/README.MD, glue/bin/cqlreplicator
- Updated README.MD
Added `--skip-keyspaces-ledger ` to skip migration.ledger creation
=> - Added --skip-keyspaces-ledger to `cqlreplicator`

README.MD
=> Updated README.MD, lic section

glue/README.MD, glue/bin/cqlreplicator, glue/sbin/keyspaces/CQLReplicator.scala, glue/sbin/memorydb/CQLReplicator.scala, glue/sbin/opensearch/CQLReplicator.scala, glue/sbin/parquet/CQLReplicator.scala
#101, #98, #94, #52
- Updated README.MD
- Added the LZ4 compression with Base64 for the offloading large payload to S3
- Added support for `boolean` type in primary key for Parquet/MemoryDB/OpenSearch
- Fixed the issue with primary keys distribution
=> Expended the stats

glue/bin/cqlreplicator, glue/conf/CassandraConnector.conf
Fixed the issue `Could not initialize class com.amazonaws.services.glue.util.StringToBoolean$` and optimized jars imports
#106 
- Added `PlainTextAuthProvider` in `CassandraConnector.conf`
- Reduced `page-size` in `CassandraConnector.conf`
- Added short abbreviation for all start parameters 
- Optimized Jars imports
=> Fixed the issue `Could not initialize class com.amazonaws.services.glue.util.StringToBoolean$`

glue/README.MD, glue/sbin/keyspaces/CQLReplicator.scala, glue/sbin/parquet/CQLReplicator.scala
#123 #58 
- Updated README.MD for Amazon S3, OpenSearch, and MemoryDB
- Fixed the issue with missing column when supply run command with --writetime-column
- Parquet Connector: Added support for JSON_MAPPING
=> 123 update the parquet connector

glue/aws-cloudformation/cql-replicator-setup-template.yaml, glue/conf/KeyspacesConnector.conf
Added CloudFormation template resource creation
Added default for Keyspaces conf with default parameters for Glue. 
=> Added CloudFormation template resource creation

glue/README.MD, glue/bin/cqlreplicator, glue/sbin/opensearch/CQLReplicator.scala
#128 
1.  Added json mapping
2. Added support for deletes in the AOS connector 
=> 128 supply the opensearch connector with the json mapping

glue/aws-cloudformation/cql-replicator-setup-template.yaml, glue/bin/cqlreplicator
Added worker type parameter for larger worker load sizes
=> add worker-type parameter

glue/aws-cloudformation/cql-replicator-setup-template.yaml
=> update CF template to remove pass role

glue/README.MD, glue/sbin/keyspaces/CQLReplicator.scala
=> Predicates for point in time replication process

glue/README.MD
=> Fix typo in README.MD

glue/aws-cloudformation/cql-replicator-setup-template.yaml
N/A
Fixed some typos in the CFN template (inside `cql-replicator-setup-template.yaml`)
=> Fix typos in CFN template

glue/README.MD, glue/bin/cqlreplicator, glue/sbin/keyspaces/CQLReplicator.scala
=> Main to 168
